import { NextResponse } from "next/server";

export async function POST(request) {
  try {
    const formData = await request.formData();
    const text = formData.get("text");
    const audioFile = formData.get("audio");
    const providedVoiceId = formData.get("voiceId");
    const apiKey = formData.get("apiKey")?.trim();
    const targetLang = formData.get("targetLang");
    const stability = parseFloat(formData.get("stability")) || 0.5;
    const similarity = parseFloat(formData.get("similarity")) || 0.75;
    const styleExaggeration = parseFloat(formData.get("style")) || 0.0;

    if (!text) {
      return NextResponse.json(
        { error: "Text is required." },
        { status: 400 }
      );
    }

    if (!providedVoiceId && !audioFile) {
      return NextResponse.json(
        { error: "Either a voice sample or a selected voice is required." },
        { status: 400 }
      );
    }

    if (!apiKey) {
      return NextResponse.json(
        { error: "ElevenLabs API key is required." },
        { status: 401 }
      );
    }

    let voice_id = providedVoiceId;
    let isTempVoice = false;

    // Step 1: If no existing voice is selected, create a temp clone
    if (!voice_id) {
      const createVoiceFormData = new FormData();
      createVoiceFormData.append("name", "Monstah Temp Clone");
      createVoiceFormData.append("files", audioFile);
      createVoiceFormData.append("description", "Temporary voice clone generated by Monstah Voice Cloner");

      const createResponse = await fetch("https://api.elevenlabs.io/v1/voices/add", {
        method: "POST",
        headers: {
          "xi-api-key": apiKey,
        },
        body: createVoiceFormData,
      });

      if (!createResponse.ok) {
        const errorData = await createResponse.json();
        return NextResponse.json(
          { error: `ElevenLabs failed to create voice: ${errorData?.detail?.message || JSON.stringify(errorData)}` },
          { status: createResponse.status }
        );
      }

      const createData = await createResponse.json();
      voice_id = createData.voice_id;
      isTempVoice = true;
    }

    try {
      // Step 2a: Translate text if requested
      let finalString = text;
      if (targetLang && targetLang.trim() !== "") {
        try {
          const transRes = await fetch("https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=" + targetLang + "&dt=t&q=" + encodeURIComponent(text));
          if (transRes.ok) {
            const transData = await transRes.json();
            finalString = transData[0].map(s => s[0]).join("");
          }
        } catch (e) {
          console.error("Translation failed, falling back to original text", e);
        }
      }

      // Step 2b: Generate speech using the newly created voice
      const ttsResponse = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voice_id}/with-timestamps?output_format=mp3_44100_128`, {
        method: "POST",
        headers: {
          "xi-api-key": apiKey,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text: finalString,
          model_id: "eleven_multilingual_v2",
          voice_settings: {
            stability: stability,
            similarity_boost: similarity,
            style: styleExaggeration,
            use_speaker_boost: true
          }
        }),
      });

      if (!ttsResponse.ok) {
        const errorData = await ttsResponse.json();
        throw new Error(`TTS failed: ${errorData?.detail?.message || JSON.stringify(errorData)}`);
      }

      const ttsData = await ttsResponse.json();
      const audioBase64 = ttsData.audio_base64;
      
      // Generate SRT
      let srtText = "";
      // ElevenLabs can return alignment in 'alignment' or 'normalized_alignment'
      const alignment = ttsData.alignment || ttsData.normalized_alignment;
      
      if (alignment) {
        // They might use 'characters' or 'chars'
        const chars = alignment.characters || alignment.chars;
        const starts = alignment.character_start_times_seconds || alignment.char_start_times_seconds || alignment.character_start_times_ms?.map(ms => ms / 1000);
        const ends = alignment.character_end_times_seconds || alignment.char_end_times_seconds || alignment.character_end_times_ms?.map(ms => ms / 1000);

        if (chars && starts) {
          let counter = 1;
          let currentWord = "";
          let wordStartTime = null;
          let wordEndTime = null;
          
          for (let i = 0; i < chars.length; i++) {
            const char = chars[i];
            const start = starts[i];
            const end = (ends && ends[i]) ? ends[i] : (start + 0.05);

            if (wordStartTime === null && char.trim() !== "") {
              wordStartTime = start;
            }

            // Word boundary detection (space, newline, or last character)
            const isLast = i === chars.length - 1;
            const isBoundary = char === " " || char === "\n" || isLast;

            if (isBoundary) {
              if (isLast && char.trim() !== "") {
                currentWord += char;
                wordEndTime = end;
              }
              
              if (currentWord.trim().length > 0) {
                const formatTime = (seconds) => {
                  if (isNaN(seconds) || seconds < 0) seconds = 0;
                  const date = new Date(0);
                  date.setMilliseconds(seconds * 1000);
                  // Ensure we get HH:mm:ss,ms format for SRT
                  return date.toISOString().substring(11, 23).replace('.', ',');
                };

                const sStartTime = formatTime(wordStartTime !== null ? wordStartTime : start);
                const sEndTime = formatTime(wordEndTime !== null ? wordEndTime : end);
                
                srtText += `${counter}\n${sStartTime} --> ${sEndTime}\n${currentWord.trim()}\n\n`;
                counter++;
              }
              currentWord = "";
              wordStartTime = null;
              wordEndTime = null;
            } else {
              currentWord += char;
              wordEndTime = end;
            }
          }
        }
      }

      // Step 3: Delete the temporary voice clone (if we created one)
      if (isTempVoice) {
        await fetch(`https://api.elevenlabs.io/v1/voices/${voice_id}`, {
          method: "DELETE",
          headers: {
            "xi-api-key": apiKey,
          },
        });
      }

      return NextResponse.json({
        audio: audioBase64,
        srt: srtText,
        contentType: "audio/mpeg",
        status: "success",
      });

    } catch (innerError) {
      // Attempt to clean up the voice even if generation fails
      if (isTempVoice) {
        await fetch(`https://api.elevenlabs.io/v1/voices/${voice_id}`, {
          method: "DELETE",
          headers: { "xi-api-key": apiKey },
        }).catch(e => console.error("Failed to cleanup voice:", e));
      }

      throw innerError;
    }

  } catch (error) {
    console.error("Voice clone error:", error);
    return NextResponse.json(
      { error: `Voice cloning failed: ${error.message}` },
      { status: 500 }
    );
  }
}
